### ISSUE TITLE
Manali trekking & climbing trip checklist

### ISSUE THREAD

**Issue by shreshthmohan** [shreshthmohan/next-blog#130]
- [ ] Refer Subhash's list
- [ ] Refer to #88 

- [ ] Socks
- [ ] Underwear
- [ ] Sunhat
- [ ] Sunscreen
- [ ] Fleece
- [ ] Merino upper
- [ ] Merino lower
- [ ] Trekking boots
- [ ] Sandals
- [ ] Rock shoes
- [ ] Chalk bag
- [ ] Sleeping bag
- [ ] Sleeping mat
- [ ] T-shirts
- [ ] Hiking pants
- [ ] Snow hiking pants?
- [ ] Merino neck warmer
- [ ] Merino skull cap
- [ ] Muffler (buy extra woolen cap)
