### ISSUE TITLE
My day-hike checklist for India

### ISSUE THREAD

**Issue by shreshthmohan** [shreshthmohan/next-blog#45]
- [ ] Sunhat
- [ ] Sunglasses
- [ ] Water (3 liters)
- [ ] Electrolyte salts
- [ ] Food (fruits and nuts)
- [ ] Handkerchief
- [ ] Tissue paper napkins
- [ ] Headlamp/torch
- [ ] Mini first aid kit 

## Rainy weather
- [ ] Plastic bag (to store electronics during rain)
- [ ] Rainwear

## If you wish to swim in a water body
- [ ] Swimming trunks
- [ ] Ear plugs
- [ ] Towel

## Luxury
- [ ] Extra t-shirt
- [ ] Helmet

## Cold Himalayan weather
- [ ] Muffler
- [ ] Skull cap
- [ ] Extra layers

## Notes
1. Water with salts is essential in (sub)tropical Indian weather, even in the mountains. 
2. Headlamp is for if and when it gets dark. You might not plan to stay out in the dark, but getting lost in the dark is not fun. Prefer a headlamp over a torch, it keeps your hands free. Decent, affordable headlamps are available locally.
3. Clothing: prefer hiking trousers over jeans. If you're going to an area with thorny plans, prefer full-length trousers over shorts.
4. Footwear: I prefer hiking sandals in hot weather and ankle-length hiking boots in the Himalayas. Don't take your Nikes and Pumas on hikes, you'll destroy them.

**Comment by shreshthmohan** [comment]
Snacks

- Lemonade salty
Butter milk
